language: bash

deploy:
  provider: script
  script: wget -O /dev/null -q http://obat.tyrnan.co.uk/.travis/pull.php
  on:
    branch: master
    
notifications:
  email:
    recipients:
    - tobias@neontribe.co.uk
    on_success: never
on_failure: always
